### ISSUE TITLE
AWS Support for Policy ARN/Larger Policy Document Support

### ISSUE THREAD

**Issue by jcornell123** [AirLiftKeyServices/ALKS#1]
Support via the API to reference Policy Document ARNs or increased size limit above 2048.

http://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html
Policy

    "An IAM policy in JSON format that is passed with the GetFederationToken call and evaluated along with the policy or policies that are attached to the IAM user whose credentials are used to call GetFederationToken. The passed policy is used to scope down the permissions that are available to the IAM user, by allowing only a subset of the permissions that are granted to the IAM user. The passed policy cannot grant more permissions than those granted to the IAM user. The final permissions for the federated user are the most restrictive set based on the intersection of the passed policy and the IAM user policy.

    If you do not pass a policy, the resulting temporary security credentials have no effective permissions. The only exception is when the temporary security credentials are used to access a resource that has a resource-based policy that specifically allows the federated user to access the resource.

    Note: The policy plain text must be 2048 bytes or shorter. However, an internal conversion compresses it into a packed binary format with a separate limit. The PackedPolicySize response element indicates by percentage how close to the upper size limit the policy is, with 100% equaling the maximum allowed size."

**Comment by jcornell123** [comment]
@sskcar Need to post the details on the design to work around the 2048 byte policy limit for the packed policy size so this issue can be closed.

**Comment by sskcar** [comment]
Now the application supports multiple users for the same AWS account. So you can create long term keys with different level access (eg cloud engineer role having a long policy) and application will use those keys to created federated tokens. You can still pass an admin level policy, but the tokens generated will still have cloud engineer role as AWS will limit to cloud engineer role.
